### ISSUE TITLE
i run and see nothing.

### ISSUE THREAD

**Issue by jacksonpan** [digitalmaster/MongoCMS#4]
![image](https://cloud.githubusercontent.com/assets/696493/5831044/f2f358fc-a164-11e4-8bff-521c73b2bf9b.png)

OS X 10.10.2
thanks.
please fix it, thanks.

**Comment by digitalmaster** [comment]
Hmm.. Sorry for late response.. I'll look into this asap. What version are you running?

**Comment by digitalmaster** [comment]
@jacksonpan I'm not able to reproduce this bug (i'm on 10.10.3).. Can you open up the dev console (cmd + option + j ).. then send me a screenshot of the console warnings and errors. Would be really helpful. Thanks.

Note: There's an update to nodewebkit (the underlying framework).. which might solve this issue but I want to be sure it's not something else.

Thanks.
